name: 'Deploy a thing'
description: ''
inputs:
  repository:
    description: 'Repository to deploy to'
    required: true
  package:
    description: 'Pahkat package name'
    required: true
  platform:
    description: 'Platform'
    required: true
  version:
    description: 'Deploy version'
    required: true
  payload:
    description: 'Path to payload artifact to deploy'
    required: true
  payloadMetadata:
    description: 'Path to payload metadata (created by a call like `pahkat payload windows-executable ...`)'
    required: false
  testDeploy:
    description: "Go as far as possible but don't actually deploy to Pahkat"
    required: false
  forceDeploy:
    description: "Forces a deployment"
    required: false
runs:
  using: 'node12'
  main: 'index.js'
