name: 'Deploy a thing'
description: ''
inputs:
  package-id:
    description: Package identifier (the part that comes after /packages/ in the package key URL)
    required: true
  platform:
    description: 'Platform'
    required: true
  version:
    description: 'Version'
    required: true
  payload-path:
    description: 'Path to payload artifact to deploy'
    required: true
  repo:
    description: 'Pahkat repository to deploy to'
    required: true
  channel:
    description: 'Pahkat channel'
    required: false
  macos-pkg-id:
    description: for macOS packages, this field is manadatory
    required: false
  macos-requires-reboot:
    description: ''
    required: false
  macos-targets:
    description: ''
    required: false
  force-deploy:
    description: "Forces a deployment"
    required: false
runs:
  using: 'node12'
  main: 'index.js'
